### ISSUE TITLE
Unable to create releases - must accept GitHub Developer Marketplace Agreement first

### ISSUE THREAD

**Issue by tranhl** [git-town/action#33]
![image](https://github.com/git-town/action/assets/24240419/58097dde-d880-4212-8590-ee74ae86abfc)

@kevgo It appears that we need to accept the GitHub Developer Marketplace Agreement again, any chance you could help out with this? The agreement must have changed -- IIRC we've accepted this in the past 🤷‍♂️

**Comment by kevgo** [comment]
Done, and I also published the latest version v1.0.3 in the process! Please let me know if you need anything else.

https://github.com/marketplace/actions/git-town-github-action

**Comment by tranhl** [comment]
Thanks a bunch!
