### ISSUE TITLE
Skip adding comment on solo PR's

### ISSUE THREAD

**Issue by stoopkidddd** [git-town/action#35]
Going to take a stab at making a PR for this, but wanted to put an issue up first.

It would be nice if there was a config option to tell the github action not to add a stack to the description if the PR isn't actually part of a stack, but just a solo PR pointing to the trunk by itself with no children

There are other people on my team not stacking their PR's, and having the comment added to their solo PRs is very confusing and does not lend to an opt-in approach.

Config option proposal - `skipSinglePR: boolean` added in `config.ts -> configSchema`

**Comment by long-connecx** [comment]
@stoopkidddd Thanks for the suggestion! I can definitely see how opting into this behaviour would ease adoption.

The best place to make this change would be in `inputs.ts`, as `config.ts` is used to parse the Git Town config file.

We gladly welcome PRs, if you feel up for the task then by all means submit one!

**Comment by tranhl** [comment]
@stoopkidddd Thanks for the suggestion! I can definitely see how always printing the stack can be confusing for other team members who don't stack their PRs.

Adding this feature will involve:

- Add add an input to toggle the feature in `action.yml`. We could call it something like `skip-(single|solo)-(stacks|changes)`
- Provide a getter for the input in `inputs.ts`: `getSkipSoloChanges()`
- Check this flag & the stack graph before updating the visualization in [main.ts:104](https://github.com/git-town/action/blob/3191ceda008221b6f82e9a23ddf45b2ab300107a/src/main.ts#L104).

PRs are very much welcome, so if you feel up for the task by all means submit one!
