### ISSUE TITLE
Accept GitHub Marketplace Developer Agreement

### ISSUE THREAD

**Issue by tranhl** [git-town/action#7]
@kevgo We need to accept the GitHub Marketplace Developer Agreement before being able to publish this action onto the marketplace. Would you be able to help out with that? 🙏

I believe you can accept the agreement by going to "Releases" > "Draft a release", then clicking on "GitHub Marketplace Developer Agreement" (which is greyed out for me here):

![image](https://github.com/git-town/action/assets/24240419/80a1aff1-2895-4802-ae28-92dd01f31dd8)

**Comment by kevgo** [comment]
@tranhl I have just accepted the GitHub Marketplace Developer Agreement. Strange that you as an admin can't do it. You should be able to publish the action now. Please hit me up if you need anything else!
